export default {
   arrowParens: 'always',
   htmlWhitespaceSensitivity: 'css',
   bracketSameLine: false,
   bracketSpacing: true,
   printWidth: 80,
   proseWrap: 'preserve',
   quoteProps: 'as-needed',
   semi: true,
   singleQuote: true,
   tabWidth: 4,
   trailingComma: 'es5',
   useTabs: false,
   plugins: ['prettier-plugin-tailwindcss'],
};
